name: pyramid
# ==========================
# Install a default D8 LAMP
# ==========================
recipe: drupal8
# ==========================
# Custom settings
# ==========================
config:
  webroot: web
  # ==========================
  # Enable XDebug
  # @see https://docs.devwithlando.io/tutorials/lando-with-vscode.html 
  # ==========================
  # xdebug: true
  # conf: 
  #   php: .vscode/php.ini
# ==========================
# NodeJS
# ==========================
services:
  node:
    type: node:6.10
    build:
      - npm run build
# ==========================
# Expose NPM to your CLI
# ==========================
tooling:
  npm:
    service: node    
# ==========================
# Custom domains
# ==========================
#proxy:
#  appserver:
#    - "yoursite.lndo.site"
#    - "*.yousite.lndo.site"
# ==========================
# Custom event
# ==========================
events:
  # ==========================
  # After lando start
  # ==========================
  post-start:
    # 
    # Commands for first install
    # 
    - echo "=========================="
    - echo "First install"
    - echo "=========================="
    - appserver: "cd $LANDO_MOUNT/ && composer install"
    - appserver: "cd $LANDO_MOUNT/ && composer generate-salt"
    - appserver: "cd $LANDO_MOUNT/ && composer fix-permissions"
    - appserver: "cd $LANDO_MOUNT/ && ./bin/drush site-install config_installer -r docroot"
    - echo ""
    - echo "=========================="
    - echo "Building theme assets..."
    - echo "=========================="
    - node: "cd $LANDO_MOUNT && npm install"
    - node: "cd $LANDO_MOUNT && npm run start"
    #
    # Uncomment all lines below after first install
    #
    #- echo "=========================="
    #- echo "Update database..."
    #- echo "=========================="
    #- appserver: "cd $LANDO_MOUNT/ && ./bin/drush cim -r docroot"
    #- appserver: "cd $LANDO_MOUNT/ && ./bin/drush entup -r docroot"
    #- appserver: "cd $LANDO_MOUNT/ && ./bin/drush updb -r docroot"
    #- appserver: "cd $LANDO_MOUNT/ && ./bin/drush locale-update -r docroot"
    #- appserver: "cd $LANDO_MOUNT/ && ./bin/drush cr -r docroot"
    #- echo ""
    #- echo "=========================="
    #- echo "Building theme assets..."
    #- echo "=========================="
    #- node: "cd $LANDO_MOUNT && npm install"
    #- node: "cd $LANDO_MOUNT && npm run reset"
    #- node: "cd $LANDO_MOUNT && npm run build"
    #- echo ""
    #- echo "=========================="
    #- echo "Doing code review..."
    #- echo "=========================="
    #- appserver: "cd $LANDO_MOUNT/ && composer code-review"
    #- node: "cd $LANDO_MOUNT && npm run lint"
    #- node: "cd $LANDO_MOUNT && npm run stats"    
