name: pyramid
# ==========================
# Install a default D8 LAMP
# ==========================
recipe: drupal8
# ==========================
# Custom settings
# ==========================
config:
  webroot: web
  # ==========================
  # Enable XDebug
  # @see https://docs.devwithlando.io/tutorials/lando-with-vscode.html 
  # ==========================
  # xdebug: true
  # conf: 
  #   php: .vscode/php.ini
# ==========================
# NodeJS
# ==========================
services:
  node:
    type: node:6.10
    build:
      - npm run build
# ==========================
# Expose NPM to your CLI
# ==========================
tooling:
  npm:
    service: node    
# ==========================
# Custom domains
# ==========================
#proxy:
#  appserver:
#    - "yoursite.lndo.site"
#    - "*.yousite.lndo.site"
